In [3]:
import pandas as pd
df=pd.read_csv('jamesbond.csv')
df.head()

Film  Year         Actor       Director  Box Office  \
0                 Dr. No  1962  Sean Connery  Terence Young       448.8   
1  From Russia with Love  1963  Sean Connery  Terence Young       543.8   
2             Goldfinger  1964  Sean Connery   Guy Hamilton       820.4   
3            Thunderball  1965  Sean Connery  Terence Young       848.1   
4          Casino Royale  1967   David Niven     Ken Hughes       315.0   

   Budget  Bond Actor Salary  
0     7.0                0.6  
1    12.6                1.6  
2    18.6                3.2  
3    41.9                4.7  
4    85.0                NaN

In [7]:
df.loc[0:5]

Film  Year         Actor       Director  Box Office  \
0                 Dr. No  1962  Sean Connery  Terence Young       448.8   
1  From Russia with Love  1963  Sean Connery  Terence Young       543.8   
2             Goldfinger  1964  Sean Connery   Guy Hamilton       820.4   
3            Thunderball  1965  Sean Connery  Terence Young       848.1   
4          Casino Royale  1967   David Niven     Ken Hughes       315.0   
5    You Only Live Twice  1967  Sean Connery  Lewis Gilbert       514.2   

   Budget  Bond Actor Salary  
0     7.0                0.6  
1    12.6                1.6  
2    18.6                3.2  
3    41.9                4.7  
4    85.0                NaN  
5    59.9                4.4

In [32]:
ha=pd.read_csv("salary.csv",index_col='name')

ha.rename(columns={'name':'emp_name'},inplace=True)
ha.head()

salaries
name           
crs           2
raks          3
sachs         4
navs          5
ships         6

In [20]:
ha.columns=['employee_name','salary']
ha.head()

employee_name  salary
0           crs       2
1          raks       3
2         sachs       4
3          navs       5
4         ships       6

In [37]:
ha.drop(['raks','sachs','navs']).head()

salaries
name           
crs           2
ships         6
hars          7
bas           6
har           5

In [41]:
ha.sample(5,axis=0)

salaries
name           
navs          5
har           5
bas           6
ships         6
hars          7

In [ ]:
ha.nsmallest

In [2]:
a=[1,2,3,4,5,6]
for i in range(0,len(a)):
    if a[i]==5:
        print("number is found at location ",a.index(i),a[i])
        break
    else:
        pass

number is found at location  3 5


In [14]:
stock_prices=[]
with open("stock_prices.csv","r") as f:
    for i in f:
        tokens=i.split(",")
        day=tokens[0]
        prices=float(tokens[1])
        stock_prices.append([day,prices])
stock_prices

[['6-Mar', 310.0],
 ['7-Mar', 340.0],
 ['8-Mar', 380.0],
 ['9-Mar', 302.0],
 ['10-Mar', 297.0],
 ['11-Mar', 323.0]]

In [46]:
a=[1,2,3,6,5,4]
b=a.sort()
print(b)

None


In [88]:
x=12
y=35
if x>y:
    high=x
else:
    high=y
value=high
while True:
    if high%x==0 and high%y==0:
        print("lcm of two numbers = ",high)
        break
    
    else:
        high=high+value


lcm of two numbers =  420


In [108]:
n=3
high=n
low=0
matrix=[[0 for i in range(n+2)] for j in  range(n+2)]
for m in range(n,0,-1):
    for k in range(low,high+2):
        matrix[low][k]=m
    for p in range(low+1,high+2):
        matrix[p][high+1]=m 
    for q in range(high,low-1,-1):
        matrix[high+1][q]=m
    for r in range(high,low,-1):
        matrix[r][low]=m
    low=low+1
    high=high-1
matrix

[[3, 3, 3, 3, 3],
 [3, 2, 2, 2, 3],
 [3, 2, 1, 2, 3],
 [3, 2, 2, 2, 3],
 [3, 3, 3, 3, 3]]

In [93]:
[[0 for i in range(5)] for j in  range(5)]


[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [115]:
import numpy as np
m1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
m2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(m1+m2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [116]:
print(m1*m2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [2]:
#matrx addition
row=int(input("enter the number of rows"))
col=int(input("enter the number of cols"))
print("enter element for matrix")
matrix1=[[int(input()) for i in range(col)] for j in range(row)]
print("matrix = ")
for i in range(row):
    for j in range(col):
        print(format(matrix1[i][j],"<3"),end="")
    print()
        

enter the number of rows2
enter the number of cols2
enter element for matrix
1
2
3
4
matrix = 
1  2  
3  4  


In [1]:
row=int(input("enter the number of rows"))
col=int(input("enter the number of cols"))
print("enter element for matrix1")
matrix1=[[int(input()) for i in range(col)] for j in range(row)]
print("matrix1 = ")
for i in range(row):
    for j in range(col):
        print(format(matrix1[i][j],"<3"),end="")
    print()
print("enter element for matrix2")
matrix2=[[int(input()) for i in range(col)] for j in range(row)]
print("matrix2 = ")
for i in range(row):
    for j in range(col):
        print(format(matrix2[i][j],"<3"),end="")
    print()
print("enter element for matrix")
matrix3=[[0 for i in range(col)] for j in range(row)]
print("matrix3 = ")
for i in range(row):
    for j in range(col):
        matrix3[i][j]=matrix1[i][j]+matrix2[i][j]
        print(format(matrix3[i][j],"<3"),end="")
    print()

enter the number of rows2
enter the number of cols2
enter element for matrix1
1
2
3
4
matrix1 = 
1  2  
3  4  
enter element for matrix2
1
2
3
4
matrix2 = 
1  2  
3  4  
enter element for matrix
matrix3 = 
2  4  
6  8  


In [ ]:
for i in range(p):
    for j in range(q):
        for k in range(q):
            matrix3[i][j]=matrix3[i][j]+matrix1[i][k]*matrix2[k][j]

In [4]:
p=int(input("enter number of elements"))
q=int(input("enter number of elements")) 
r=int(input("enter number of elements"))
print("enter element for matrix1")
matrix1=[[int(input()) for i in range(q)] for j in range(p)]
print("matrix1 = ")
for i in range(p):
    for j in range(q):
        print(format(matrix1[i][j],"<3"),end="")
    print()
print("enter element for matrix2")
matrix2=[[int(input()) for i in range(r)] for j in range(q)]
print("matrix2 = ")
for i in range(q):
    for j in range(r):
        print(format(matrix2[i][j],"<3"),end="")
    print()
matrix3=[[0 for i in range(col)] for j in range(row)]
for i in range(p):
    for j in range(r):
        for k in range(q):
            matrix3[i][j]=matrix3[i][j]+matrix1[i][k]*matrix2[k][j]
print("matrix3 = ")
for i in range(p):
    for j in range(r):
        print(format(matrix3[i][j],"<3"),end="")
    print() 

enter number of elements2
enter number of elements3
enter number of elements2
enter element for matrix1
1
2
3
4
5
6
matrix1 = 
1  2  3  
4  5  6  
enter element for matrix2
7
8
9
1
2
3
matrix2 = 
7  8  
9  1  
2  3  
matrix3 = 
31 19 
85 55 
