In [49]:
class human:
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def get_name_age(self):
        print('name and age are ',self.name,self.age)
s=human('chets',24)
s.get_name_age()
    
        
    

name and age are  chets 24


In [50]:
#inheritence methode 
class fruit:
    def __init__(self):
        print("iam a fruit")
class citrus(fruit):
    def __init__(self):
        super().__init__()   #here we are calling __init__ of super class
        print("iam an citrus")
lemon=citrus()

        

iam a fruit
iam an citrus


In [51]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [57]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
a.sum(axis=0)

array([12, 15, 18])

In [71]:
a.sum(axis=1)

array([ 6, 15, 24])

In [72]:
a.sum()

45

In [73]:
sum((a,b))

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [74]:
np.sum((a,b),axis=1)

array([[ 12,  15,  18],
       [120, 150, 180]])

In [78]:
import pandas as pd
data=[1,2,3,4,5]
df=pd.DataFrame(data)
df


0
0  1
1  2
2  3
3  4
4  5

In [83]:
import pandas as pd
data={'fruit':['apple','mango','banana'],'count':[10,12,13]}
df=pd.DataFrame(data)
df


fruit  count
0   apple     10
1   mango     12
2  banana     13

In [85]:
data['count']

[10, 12, 13]

In [87]:
data['fruit']

['apple', 'mango', 'banana']

In [1]:
# Q) write a program to find the length of string?
a='hars'
count=0
for i in a:
    count+=1
print(count)

4


In [22]:
a=[0,1,2,3,4,5]
b=[4,5,2,7,4,9]
c=[]
for i in range(len(a)):
    if a[i]==b[i]:
        c.append(a[i])
    else:
        pass
print(c)

[2, 4]


In [27]:
import pandas as pd
ser=pd.Series(['chets','cats','kams'])
ser

0    chets
1     cats
2     kams
dtype: object

In [28]:
ser.map(lambda x:x.title() )  #title case means first letter of each word becomes capital

0    Chets
1     Cats
2     Kams
dtype: object

In [29]:
iris

NameError: name 'iris' is not defined